spring:
  application:
    name: service-verification-code
  redis:
    port: 6379
    host: localhost
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka