#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
##    fetch-registry: false #标识该客户端是否从eureka拉取注册信息
##    register-with-eureka: false #标识该服务信息是否需要向eureka注册，给其他人发现
spring:
  application:
    name: eurekaCloud

eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/,http://eureka8763:8763/eureka/
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: false
---
server:
  port: 8761

spring:
  profiles: 8761
eureka:
  instance:
    hostname: eureka8761
---
server:
  port: 8762
spring:
  profiles: 8762
eureka:
  instance:
    hostname: eureka8762

---
server:
  port: 8763
spring:
  profiles: 8763
eureka:
  instance:
    hostname: eureka8763