#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
##    fetch-registry: false #标识该客户端是否从eureka拉取注册信息
##    register-with-eureka: false #标识该服务信息是否需要向eureka注册，给其他人发现
#spring:
#  application:
#    name: eureka01

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  server:
    enable-self-preservation: false
---
server:
  port: 8761

spring:
  profiles: 8761
  application:
    name: eureka8761

---
server:
  port: 8762
spring:
  profiles: 8762
  application:
    name: eureka8762

---
server:
  port: 8763
spring:
  profiles: 8763
  application:
    name: eureka8763