server:
  port: 8080
spring:
  application:
    name: api-passenger
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/exercise?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false
  rabbitmq:
    password: diao
    username: diao
    virtual-host: /diao
    listener:
      simple:
        acknowledge-mode: manual

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml